abstract Playback {
  + addStateListener(Listener): void
  + handleRightClick(event: Event): void
  + handleMouseEnter(): void
  + handleMouseLeave(): void
  + handlePlayerStart(): void
  + handlePlayerPause(): void
  + handlePlayerSeekAs(): void

  ' --- Synchronized Playback Methods ---
  + startAll(): void
  + pauseAll(): void
  + stopAll(): void
  + seekAll(time: number): void
}

class CmmcoPlayback {
}

class VideoPlayback {
}

class AudioPlayback {
}

class ImagePlayback {
}

Playback <|-- CmmcoPlayback
Playback <|-- VideoPlayback
Playback <|-- AudioPlayback
Playback <|-- ImagePlayback
