@startuml
top to bottom direction

interface MMIRAdapter {
}
abstract Playback {
  + addStateListener(Listener): void
  + handleRightClick(event: Event): void
  + handleMouseEnter(): void
  + handleMouseLeave(): void
  + handlePlayerStart(): void
  + handlePlayerPause(): void
  + handlePlayerSeekAs(): void

  ' --- Synchronized Playback Methods ---
  + startAll(): void
  + pauseAll(): void
  + stopAll(): void
  + seekAll(time: number): void
}

class CmmcoPlayback {

}

Playback <|-- CmmcoPlayback

class Multimedia {
  - view: string
  - mmco: Object
  - start: number
  - end: number
  - timecode: number
  + setTimeCode(time: number): void
}

interface PdPlayer {
  - media: Multimedia
  + play(): void
  + pause(): void
  + stop(): void
  + seek(time: number): void
}

interface SrdPlayer {
  - media: Multimedia
  + play(): void
  + pause(): void
  + stop(): void
  + seek(time: number): void
}

interface MmcoPlayer {
  - media: Multimedia
  + play(): void
  + pause(): void
  + stop(): void
  + seek(time: number): void
}
MMIRAdapter -- Playback : uses

CmmcoPlayback --> Multimedia
SrdPdPanel "1" --> "0..*" PdPlayer
SrdPdPanel "1" --> "0..1" SrdPlayer
MmcoPanel "1" --> "0..1" MmcoPlayer





class DetailsView {
    - item: MVR
}

together {
  class MmcoPanel {
  + start(): void
  + pause(): void
  + stop(): void
  + seek(time: number): void
  }

  class SrdPdPanel {
    + handlePlayerSelect(id: number)
    + startAll(): void
    + pauseAll(): void
    + stopAll(): void
    + seekAll(time: number): void  
  }

  class RSGPlayer {
  }

  class HeartBearVisualizer {
  }

  class EyeGazeVisualizer {
  }

  SrdPlayer <|.. RSGPlayer
  PdPlayer <|.. HeartBearVisualizer
  PdPlayer <|.. EyeGazeVisualizer
  MmcoPlayer <|.. VideoPlayer
  MmcoPlayer <|.. AudioPlayer

  CmmcoPlayback "1" *-- "1" MmcoPanel
  CmmcoPlayback "1" *-- "1" SrdPdPanel

  class VideoPlayer {
  }
  class AudioPlayer {
  }
}

DetailsView *-- Playback

@enduml