@startuml
title Synchronized Playback Sequence

actor User
participant "Playback" as PB
participant "SrdPdPanel" as SPP
participant "SrdPlayer" as SP
participant "PdPlayer" as PDP
participant "MmcoPanel" as MP
participant "MmcoPlayer" as MMP

' ===========================
' 1) Start All
' ===========================
User -> PB : startAll()
activate PB

PB -> SPP : startAll()
activate SPP

' Suppose SrdPdPanel holds one SrdPlayer and multiple PdPlayers
SPP -> SP : play()
activate SP
deactivate SP

SPP -> PDP : play()
activate PDP
deactivate PDP

deactivate SPP

PB -> MP : start()
activate MP

' MmcoPanel might hold one MmcoPlayer
MP -> MMP : play()
activate MMP
deactivate MMP

deactivate MP
deactivate PB

' ===========================
' 2) Pause All
' ===========================
User -> PB : pauseAll()
activate PB

PB -> SPP : pauseAll()
activate SPP

SPP -> SP : pause()
activate SP
deactivate SP

SPP -> PDP : pause()
activate PDP
deactivate PDP

deactivate SPP

PB -> MP : pause()
activate MP

MP -> MMP : pause()
activate MMP
deactivate MMP

deactivate MP
deactivate PB

' ===========================
' 3) Stop All
' ===========================
User -> PB : stopAll()
activate PB

PB -> SPP : stopAll()
activate SPP

SPP -> SP : stop()
activate SP
deactivate SP

SPP -> PDP : stop()
activate PDP
deactivate PDP

deactivate SPP

PB -> MP : stop()
activate MP

MP -> MMP : stop()
activate MMP
deactivate MMP

deactivate MP
deactivate PB

@enduml